### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by zigapk** [lirios/files#3]
I noticed some lack of keyboard shortcuts. I am used mostly to this ones:
- arrow key navigation, backspace (parent folder) , return (open file/folder) (I don't remember whether those already exist and apologize if they do)
- ctrl+n creates new file/folder
- ctrl+w closes the window
- ctrl+l could let you edit full current path as string (this is just just an idea)
- it should be possible to select the button and confirm the selection in all the dialogs (or use the esc key to dismiss it). I can currently only think of "new folder" dialog, but believe there are some others.

In my opinion it would be great to have some of those implemented, but this is only my opinion.

**Comment by plfiorini** [comment]
Most shortcuts were already implemented except for arrow key navigation, open file/folder with enter, edit full current path, confirm and close dialogs.
Parent folder is Alt+Up as in up one level rather than backspace.

**Comment by plfiorini** [comment]
Alt+LeftArrow is back
